logging:
  level:
    root: INFO
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    activate:
      on-profile: default
  application:
    name: inditex-asset
  r2dbc:
    url: r2dbc:h2:mem:///testdb;ACCESS_MODE_DATA=rw
    repositories:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


file:
  properties:
    url: https://container.inditex.org/file/{fileId}